### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by AytajHsnv** [HqiTao/CT-crackseg#4]
Hi,
I would like to ask that how did you get the pretrained model weights? Which method did you use?

Thank you in advance.

**Comment by AytajHsnv** [comment]
@HqiTao

**Comment by HqiTao** [comment]
Hi, thanks for being interested in our work and please excuse the late reply!

We simply save the model weights using the torch.save() function. You can find the code [here](https://github.com/HqiTao/CT-crackseg/blob/main/train_crack.py#L106-L121).

**Comment by AytajHsnv** [comment]
Thank you so much for repy, but i would like to know that how many times did you train that you got best weights at the end?

**Comment by HqiTao** [comment]
Sorry, I can't remember this.
